### ISSUE TITLE
Kebab menu doesn’t fade away

### ISSUE THREAD

**Issue by ajrgvan** [ajrgvan/privynote-web#2]
When the kebab menu is clicked, it remains permanently in the view. It should fade away when a user clicks somewhere else on the screen.

**Comment by lavandalabs** [comment]
Having issues with this functionality.

**Comment by ajrgvan** [comment]
This issue has been partially solved. It persists while clicking on other kebab menus.

**Comment by ajrgvan** [comment]
I see you've created a random ID for each of the delete buttons. Why exactly is this required? The global variable would suffice, right? 

The reason why I've chosen a cryptographic function is because these note IDs are hashed and stored in the server. Therefore, I want to prevent collisions. Although I'm checking for collisions, and yes, I could use Math.random(), I just want to be consistent with the security, preferring cryptographically random values wherever possible.

**Comment by ajrgvan** [comment]
Fixed this issue.
